export const INVERTED_WORLD_TABLES = [
  "channel_items",
  "coverage_snapshots",
  "x_signals",
  "article_drafts",
  "generated_assets",
  "claim_dossiers",
  "claim_sources",
  "claim_chat_messages",
  "front_page_editions",
] as const

export const INVERTED_WORLD_SCHEMA_SQL = [
  "CREATE EXTENSION IF NOT EXISTS pgcrypto",
  `CREATE TABLE IF NOT EXISTS channel_items (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    source TEXT NOT NULL,
    source_id TEXT,
    source_url TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    published_at TIMESTAMPTZ,
    topic_id TEXT,
    transcript TEXT,
    thumbnail_url TEXT,
    embed_url TEXT,
    kind TEXT DEFAULT 'episode',
    metadata JSONB DEFAULT '{}'::jsonb,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS channel_items_topic_published_idx ON channel_items (topic_id, published_at DESC)",
  "CREATE INDEX IF NOT EXISTS channel_items_source_id_idx ON channel_items (source, source_id)",
  `CREATE TABLE IF NOT EXISTS coverage_snapshots (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    topic_id TEXT NOT NULL,
    query TEXT NOT NULL,
    source TEXT NOT NULL,
    captured_at TIMESTAMPTZ DEFAULT now(),
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    official_records JSONB DEFAULT '[]'::jsonb,
    summary TEXT,
    velocity_score NUMERIC DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS coverage_snapshots_topic_captured_idx ON coverage_snapshots (topic_id, captured_at DESC)",
  `CREATE TABLE IF NOT EXISTS x_signals (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    topic_id TEXT NOT NULL,
    x_id TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    username TEXT,
    author_name TEXT,
    text TEXT NOT NULL,
    posted_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ DEFAULT now(),
    source TEXT DEFAULT 'x-api',
    score NUMERIC DEFAULT 0,
    metrics JSONB DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS x_signals_topic_score_idx ON x_signals (topic_id, score DESC, posted_at DESC)",
  `CREATE TABLE IF NOT EXISTS generated_assets (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    asset_type TEXT NOT NULL,
    prompt TEXT NOT NULL,
    provider TEXT,
    bucket_name TEXT,
    object_key TEXT,
    url TEXT,
    status TEXT DEFAULT 'generated',
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS generated_assets_type_created_idx ON generated_assets (asset_type, created_at DESC)",
  `CREATE TABLE IF NOT EXISTS article_drafts (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    deck TEXT,
    topic_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    body JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_ids JSONB DEFAULT '[]'::jsonb,
    source_name TEXT,
    source_url TEXT,
    heat INTEGER DEFAULT 0,
    thumbnail_asset_id TEXT,
    thumbnail_prompt TEXT,
    model TEXT,
    prompt_version TEXT,
    generated_at TIMESTAMPTZ DEFAULT now(),
    published_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS article_drafts_status_published_idx ON article_drafts (status, published_at DESC)",
  "CREATE INDEX IF NOT EXISTS article_drafts_topic_status_idx ON article_drafts (topic_id, status, published_at DESC)",
  `CREATE TABLE IF NOT EXISTS claim_dossiers (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    deck TEXT,
    topic_id TEXT NOT NULL,
    claim TEXT NOT NULL,
    summary TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    evidence_grade TEXT NOT NULL DEFAULT 'developing',
    confidence_score NUMERIC DEFAULT 0,
    x_velocity_score NUMERIC DEFAULT 0,
    source_count INTEGER DEFAULT 0,
    x_signal_count INTEGER DEFAULT 0,
    related_video_count INTEGER DEFAULT 0,
    source_links JSONB DEFAULT '[]'::jsonb,
    x_signals JSONB DEFAULT '[]'::jsonb,
    related_videos JSONB DEFAULT '[]'::jsonb,
    weird_read TEXT,
    skeptical_read TEXT,
    viral_headlines JSONB DEFAULT '[]'::jsonb,
    chat_prompt TEXT,
    generated_at TIMESTAMPTZ DEFAULT now(),
    published_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS claim_dossiers_status_published_idx ON claim_dossiers (status, published_at DESC)",
  "CREATE INDEX IF NOT EXISTS claim_dossiers_topic_velocity_idx ON claim_dossiers (topic_id, x_velocity_score DESC, updated_at DESC)",
  `CREATE TABLE IF NOT EXISTS claim_sources (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    dossier_id TEXT NOT NULL REFERENCES claim_dossiers(id) ON DELETE CASCADE,
    source_kind TEXT NOT NULL DEFAULT 'news',
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    outlet TEXT,
    stance TEXT,
    bias_lane TEXT,
    published_at TIMESTAMPTZ,
    credibility_score NUMERIC DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS claim_sources_dossier_url_unique ON claim_sources (dossier_id, url)",
  "CREATE INDEX IF NOT EXISTS claim_sources_dossier_kind_idx ON claim_sources (dossier_id, source_kind, bias_lane)",
  `CREATE TABLE IF NOT EXISTS claim_chat_messages (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    dossier_slug TEXT NOT NULL,
    conversation_id TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    message TEXT NOT NULL,
    response TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS claim_chat_messages_dossier_created_idx ON claim_chat_messages (dossier_slug, created_at DESC)",
  `CREATE TABLE IF NOT EXISTS front_page_editions (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    slug TEXT NOT NULL UNIQUE,
    edition_date DATE NOT NULL UNIQUE,
    headline TEXT NOT NULL,
    deck TEXT,
    status TEXT NOT NULL DEFAULT 'published',
    lead_dossier_slug TEXT,
    sections JSONB NOT NULL DEFAULT '{}'::jsonb,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    generated_at TIMESTAMPTZ DEFAULT now(),
    published_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS front_page_editions_status_date_idx ON front_page_editions (status, edition_date DESC)",
]
