export const INVERTED_WORLD_TABLES = [
  "channel_items",
  "coverage_snapshots",
  "x_signals",
  "article_drafts",
  "generated_assets",
] as const

export const INVERTED_WORLD_SCHEMA_SQL = [
  "CREATE EXTENSION IF NOT EXISTS pgcrypto",
  `CREATE TABLE IF NOT EXISTS channel_items (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    source TEXT NOT NULL,
    source_id TEXT,
    source_url TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    published_at TIMESTAMPTZ,
    topic_id TEXT,
    transcript TEXT,
    thumbnail_url TEXT,
    embed_url TEXT,
    kind TEXT DEFAULT 'episode',
    metadata JSONB DEFAULT '{}'::jsonb,
    sync_status TEXT DEFAULT 'synced',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS channel_items_topic_published_idx ON channel_items (topic_id, published_at DESC)",
  "CREATE INDEX IF NOT EXISTS channel_items_source_id_idx ON channel_items (source, source_id)",
  `CREATE TABLE IF NOT EXISTS coverage_snapshots (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    topic_id TEXT NOT NULL,
    query TEXT NOT NULL,
    source TEXT NOT NULL,
    captured_at TIMESTAMPTZ DEFAULT now(),
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    official_records JSONB DEFAULT '[]'::jsonb,
    summary TEXT,
    velocity_score NUMERIC DEFAULT 0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS coverage_snapshots_topic_captured_idx ON coverage_snapshots (topic_id, captured_at DESC)",
  `CREATE TABLE IF NOT EXISTS x_signals (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    topic_id TEXT NOT NULL,
    x_id TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    username TEXT,
    author_name TEXT,
    text TEXT NOT NULL,
    posted_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ DEFAULT now(),
    source TEXT DEFAULT 'x-api',
    score NUMERIC DEFAULT 0,
    metrics JSONB DEFAULT '{}'::jsonb,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS x_signals_topic_score_idx ON x_signals (topic_id, score DESC, posted_at DESC)",
  `CREATE TABLE IF NOT EXISTS generated_assets (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    asset_type TEXT NOT NULL,
    prompt TEXT NOT NULL,
    provider TEXT,
    bucket_name TEXT,
    object_key TEXT,
    url TEXT,
    status TEXT DEFAULT 'generated',
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS generated_assets_type_created_idx ON generated_assets (asset_type, created_at DESC)",
  `CREATE TABLE IF NOT EXISTS article_drafts (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    deck TEXT,
    topic_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    body JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_ids JSONB DEFAULT '[]'::jsonb,
    source_name TEXT,
    source_url TEXT,
    heat INTEGER DEFAULT 0,
    thumbnail_asset_id TEXT,
    thumbnail_prompt TEXT,
    model TEXT,
    prompt_version TEXT,
    generated_at TIMESTAMPTZ DEFAULT now(),
    published_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
  )`,
  "CREATE INDEX IF NOT EXISTS article_drafts_status_published_idx ON article_drafts (status, published_at DESC)",
  "CREATE INDEX IF NOT EXISTS article_drafts_topic_status_idx ON article_drafts (topic_id, status, published_at DESC)",
]
